#!/bin/bash
collection=()

function collection_add(){
	echo "Add meg az előadót: "
	read ARTIST
	echo "Add meg az albumot: "
	read ALBUM
	echo "Add meg a formátumot (CD/vinyl/kazetta/digitális): "
	read FORMAT

	#declare -a collection=("Lady Gaga" "Chromatica" "CD")
	collection=("$ARTIST" "$ALBUM" "$FORMAT")

	echo "Ez lett hozzáadva a gyűjteményedhez:"
	printf "\tElőadó: %s\n\tAlbum: %s\n\tFormátum: %s\n" "${collection[@]}"

	collection_write_to_txt
	echo "Sikeres fájlba íratás!"
}

function collection_view(){
	for i in "${collection[@]}"
	do
		echo "Előadó: %s Album: %s Formátum: %s\n" "${collection[@]}"
	done
}

function collection_from_file(){
	filename='collection.txt'
	while read line;
	do
		echo $line
	done < $filename
}

function collection_write_to_txt(){
	for i in "${collection[@]}"
	do
		echo $i
	done >>collection.txt
}

while getopts :af opt
do
	case $opt in
		a)
			collection_add
			;;
		f)
			collection_from_file
			;;
		?)
			echo "Nem kezelt opció: $OPTARG"
			exit
	esac
done
