#!/bin/bash
collection=()
#hello="Hello World!"

function collection_add(){
	echo "Add meg az előadót: "
	read ARTIST
	echo "Add meg az albumot: "
	read ALBUM
	echo "Add meg a formátumot (CD/vinyl/kazetta/digitális): "
	read FORMAT

	#declare -a collection=("Lady Gaga" "Chromatica" "CD")
	collection=("$ARTIST" "$ALBUM" "$FORMAT")

	echo "Ez lett hozzáadva a gyűjteményedhez:"
	printf "\tElőadó: %s\n\tAlbum: %s\n\tFormátum: %s\n" "${collection[@]}"

	echo "Sikeres hozzáadás!"
	echo ""
}

function collection_view(){
	for i in "${collection[@]}"
	do
		echo "Előadó: %s Album: %s Formátum: %s\n" "${collection[@]}"
	done
}

collection_add
#collection_view

function collection_filter(){
	echo "You can filter your collection here!"
}

function collection_write_to_txt(){
	for i in "${collection[@]}"
	do
		echo $i
	done >>collection.txt
}

collection_write_to_txt

#while getopts :a:b: opt; do
#	case $opt in
#		a)
#			collection_filter
#			;;
#		b)
#			collection_view
#			;;
#		?)
#			echo "Nem kezelt opció: $OPTARG"
#	esac
#done



